apiVersion: v1
kind: Secret
metadata:
  name: minhchien
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtcmNoaWVuMjk3IiwicGFzc3dvcmQiOiJ5ZXV5b29uYTk4IiwiZW1haWwiOiJ5b29uYWNoaWVuQGdtYWlsLmNvbSIsImF1dGgiOiJiWEpqYUdsbGJqSTVOenA1WlhWNWIyOXVZVGs0In19fQ==
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-test-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  selector:
    matchLabels:
      app: flask-test-app
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
      - name: flask-test-app
        image: flask-kubernetes
        imagePullPolicy: Always
        command: [ "echo", "SUCCESS" ]
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: minhchien